version: "3.9"
services:
  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_DB: "igg-tp-info"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
    ports:
      - "5433:5432"